void enable_cache();
size_t getCPSR();
size_t getMode();
size_t getPerformanceCounter();
void initialRegisterValues();
size_t liveFn();
size_t liveInstruction();
size_t perfTest();
void setMode(size_t mode);
size_t toggleIRQs();
