void enable_cache();
size_t get_cpsr();
size_t get_mode();
size_t get_performance_counter();
void initial_register_values();
size_t live_fn();
size_t live_instruction();
size_t perf_test();
void set_mode(size_t mode);
size_t toggle_irqs();
