#!/bin/bash

echo 'Cleaning project files...'
git ls-files --other | xargs rm

echo 'Building SD card image...'
./tools/build-sd-card-image

rm *-raspios-*.img

xz kitsune-sd-card.img

echo 'Creating tarball...'
tar --create --gzip --file kitsune-os.tar.gz *
